name: grilledcheese
favicon: null
layout_spectrum: 0.05752591113559902
typography_spectrum: 0.4590855098795146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.15481010638177395
  lightness: 0.17778843804262578
  saturation: 0.4187212937977165
  rhythmicContrast: 0.5061601018533111
purpose: []
